[general]
live_config_reload = true
import = [
  "~/.config/alacritty/themes/rose-pine.toml",
]

[window]
opacity = 0.8
blur = true
option_as_alt = "OnlyLeft"
padding = { x = 10, y = 5 }

[font]
normal = { family = "FiraCode Nerd Font Mono" }
size = 14.00
